### ISSUE TITLE
In Windows : search query of "hell" throws UnicodeDecodeError

### ISSUE THREAD

**Issue by upendra-k14** [upendra-k14/pip_gui#22]
System : Windows 7

Search query "hell" in InstallFromPyPI page returns UnicodeDecodeError. I have not checked for this behaviour in Linux. Other queries work perfectly. Seems like some characters like : `\u5927\u5bb6\u597d` (as reported in the following error) couldn't be decoded properly.

```
2016-07-31 11:17:45,010 - __main__ - INFO - Welcome today
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\upendra\appdata\local\programs\python35\lib\logging\__init__.py
", line 982, in emit
    stream.write(msg)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\upendra\appdata\local\programs\python35\lib\encodings\cp1252.py
", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 60-68: c
haracter maps to <undefined>
Call stack:
  File "c:\users\upendra\appdata\local\programs\python35\lib\runpy.py", line 170
, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\upendra\appdata\local\programs\python35\lib\runpy.py", line 85,
 in _run_code
    exec(code, run_globals)
  File "C:\Users\Upendra\AppData\Local\Programs\Python35\Scripts\pip3.exe\__main
__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
_init__.py", line 221, in main
    return command.main(cmd_args)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\b
asecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\c
ommands\search.py", line 50, in run
    print_results(hits, terminal_width=terminal_width)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\c
ommands\search.py", line 128, in print_results
    logger.info(line)
Message: 'jaychou (0.1)                                        - Hello\u5927\u5b
b6\u597d\uff0c\u6211\u662f\u5468\u6770\u4f26'
Arguments: ()
```

**Comment by upendra-k14** [comment]
System : Windows 7
pip3 version : 8.1.2
In the above error : the package description of `jaychou (0.1)` contains some characters which probably couldn't be encoded from Unicode. I tried doing : `pip3 search jaychou`. It also throws the error, which points to encoding error in ~~`pip` package~~ , but in working of subprocess module with unicode and cmd in Windows.

```
--- Logging error ---
Traceback (most recent call last):
  File "c:\users\upendra\appdata\local\programs\python35\lib\logging\__init__.py
", line 982, in emit
    stream.write(msg)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
vendor\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\upendra\appdata\local\programs\python35\lib\encodings\cp437.py"
, line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-30: c
haracter maps to <undefined>
Call stack:
  File "c:\users\upendra\appdata\local\programs\python35\lib\runpy.py", line 170
, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\upendra\appdata\local\programs\python35\lib\runpy.py", line 85,
 in _run_code
    exec(code, run_globals)
  File "C:\Users\Upendra\AppData\Local\Programs\Python35\Scripts\pip3.exe\__main
__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\_
_init__.py", line 221, in main
    return command.main(cmd_args)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\b
asecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\c
ommands\search.py", line 50, in run
    print_results(hits, terminal_width=terminal_width)
  File "c:\users\upendra\appdata\local\programs\python35\lib\site-packages\pip\c
ommands\search.py", line 128, in print_results
    logger.info(line)
Message: 'jaychou (0.1)  - Hello\u5927\u5bb6\u597d\uff0c\u6211\u662f\u5468\u6770
\u4f26'
Arguments: ()
```
