### ISSUE TITLE
GUI locks up very often

### ISSUE THREAD

**Issue by Kwpolska** [upendra-k14/pip_gui#9]
- takes a long time to start
- locks up when installing with no information on the progress whatsoever
- locks up when refreshing

**Comment by Mec-iS** [comment]
please @Kwpolska can you write which OS and Python version you are running?

**Comment by Kwpolska** [comment]
Python 3 on Linux, but this does not matter, as your blocking network code works on the main thread — which is a problem on any system.

**Comment by upendra-k14** [comment]
The problem is that when we try to remove the network code of pip which fetches the list of packages or installs something, an error is thrown by pip.main(). This issue was reported in pip issues : https://github.com/pypa/pip/issues/2553. I have copied it here. I got the same issue when I tried to run the pip code in other thread : 

```
Traceback (most recent call last):
File "/usr/lib/python2.7/logging/__init__.py", line 846, in emit msg = self.format(record)
File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 103, in format msg = logging.StreamHandler.format(self, record)
File "/usr/lib/python2.7/logging/__init__.py", line 723, in format return fmt.format(record)
File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 52, in format for line in formatted.splitlines(True)
File "/home/zadmin/ngw/env/local/lib/python2.7/site-packages/pip/utils/logging.py", line 39, in get_indentation return _log_state.indentation
AttributeError: 'thread._local' object has no attribute 'indentation'
```

" The issue is that _log_state is a thread.local() object - I'm not sure why - and the indentation attribute is set in the global scope - i.e. it is only visible to the thread that first imports pip. Any other thread has a problem. "

Therefore, I used the after() method of tkinter to schedule this task in tkinter event loop. I am going to try multiprocessing module for improvement in performance.
